const tours = [
  {
    name: "Egri bemutató",
    type: 1,
    location: "Eger, Magyarország",
    activities: [
      "Borkóstoló a szépasszonyvölgyében",
      "Egri vár bejárása",
      "Városi séta és történelmi bemutató",
    ],
    startDate: "Ezt majd később",
    endDate: "Ezt majd később",
    pricePerPerson: 15000,
    currency: "HUF",
  },
  {
    name: "Balatoni kikapcsolódás",
    type: 1,
    location: "Balaton, Magyarország",
    activities: [
      "Hajókázás a Balatonon",
      "Látogatás a Tihanyi Apátságban",
      "Piknik a parton",
    ],
    startDate: "Ezt majd később",
    endDate: "Ezt majd később",
    pricePerPerson: 12000,
    currency: "HUF",
  },
  {
    name: "Bécsi karácsonyi vásár",
    type: 1,
    location: "Bécs, Ausztria",
    activities: [
      "Karácsonyi vásár látogatása",
      "Városnézés",
      "Múzeumlátogatás a Hofburgban",
    ],
    startDate: "2024-12-15T07:00:00",
    endDate: "2024-12-15T22:00:00",
    pricePerPerson: 20000,
    currency: "HUF",
  },
  {
    name: "Tokaji bortúra",
    type: 2,
    location: "Tokaj, Magyarország",
    activities: [
      "Borkóstoló helyi pincészetekben",
      "Tokaj történelmi központjának felfedezése",
      "Hajókirándulás a Bodrogon",
    ],
    startDate: "2024-07-01T08:00:00",
    endDate: "2024-07-03T18:00:00",
    pricePerPerson: 45000,
    currency: "HUF",
    accommodation: {
      name: "Tokaji Pincészet Vendégház",
      type: "Vendégház",
      pricePerNight: 10000,
      totalNights: 2,
      location: "Tokaj belvárosa",
    },
  },
  {
    name: "Prágai hétvége",
    type: 2,
    location: "Prága, Csehország",
    activities: [
      "Óváros és Károly híd bejárása",
      "Helyi sörkóstoló",
      "Várnegyed és Szent Vitus-székesegyház",
    ],
    startDate: "2024-09-20T06:00:00",
    endDate: "2024-09-22T22:00:00",
    pricePerPerson: 70000,
    currency: "HUF",
    accommodation: {
      name: "Hotel Praha Centrum",
      type: "Szálloda",
      pricePerNight: 15000,
      totalNights: 2,
      location: "Prága belvárosa",
    },
  },
];
